"""empty message

Revision ID: 766030ea2357
Revises: 2b451599e9d8
Create Date: 2025-02-11 11:17:42.066560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766030ea2357'
down_revision = '2b451599e9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
